<?php

/**
 * @file
 * Contains slides_presentation.module..
 * @author Marouan Hammami mh.marouan@gmail.com
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function slides_presentation_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the slides_presentation module.
    case 'help.page.slides_presentation':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Editor tools content') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function slides_presentation_theme($existing, $type, $theme, $path)
{
  $theme = [];
  
  $theme['page__slides'] = [
    'template' => 'page--slides',
    'variables' => ['title' => NULL, 'slides' => NULL],
  ];

  return $theme;
}



/**
 * Implements hook_page_attachments().
 *
 */
function slides_presentation_page_attachments(array &$page) {

  $route_name = \Drupal::service('current_route_match')->getRouteName();
  if ($route_name == 'slides_presentation_content') {

    $page['#attached']['library'][] = 'slides_presentation/slides_presentation';
    
  }
}

/**
 * Implements hook_theme_registry_alter
 */
function slides_presentation_theme_registry_alter(&$theme_registry) {
  $theme_registry['sitemap']['path'] = drupal_get_path('module', 'slides_presentation') . '/templates';
}

/**
 * Implements hook_entity_operation().
 */
function slides_presentation_entity_operation(\Drupal\Core\Entity\EntityInterface $entity)
{
  $route_name = \Drupal::service('current_route_match')->getRouteName();
  if ($route_name == 'entity.slides_presentation.collection') {

    $operations = array();
    $operations['view_slide'] = array(
      'title' => t('display'),
      'url' => \Drupal\Core\Url::fromRoute('slides_presentation_content', array('id_presentation' => $entity->id())),
      'weight' => 50,
    );
    return $operations;
  }
  
}

/**
 * Prepares variables for Presentation templates.
 *
 * Default template: page--slide.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_page__slides(array &$variables) {

  $route_match = \Drupal::service('current_route_match');
  $id_presentation = $route_match->getParameter('id_presentation');


  $nids_slides = \Drupal::entityQuery('slides_slide')
          ->condition('presentation_id', $id_presentation)
          ->condition('status', 1)
          ->execute();

  $slides = \Drupal::entityTypeManager()
          ->getStorage('slides_slide')
          ->loadMultiple($nids_slides);

  $variables['content'] = [];
  $variables['slides'] = $slides;

}


